In [ ]:
import pandas
import numpy as np
import matplotlib.pyplot as plt

crimes = pandas.read_csv(r'C:\Users\Aluno.SantaLuzia\Documents\Elaine\uc2\bases\03.BaseDPEvolucaoMensalCisp.csv', sep=';', encoding='iso-8859-1')
delegacias = pandas.read_csv(r'C:\Users\Aluno.SantaLuzia\Documents\Elaine\uc2\bases\08.DP.csv')

crimesJoinDelegacias = pandas.merge(crimes, delegacias, right_on='codDP', left_on='cisp')
crimes_delegacias = crimesJoinDelegacias[['nome', 'roubo_celular', 'roubo_transeunte', 'munic']]

In [31]:
def diagnostico(df, coluna):
    media = df[coluna].mean()
    mediana = df[coluna].median()
    tolerancia = 0.1

    moda = df[coluna].mode().iloc[0]
    desvio = df[coluna].std()
    cv = (desvio / media) * 100 if media != 0 else np.nan
    minimo = df[coluna].min()
    maximo = df[coluna].max()
    amplitude = maximo - minimo
    q1 = df[coluna].quantile(0.25)
    q2 = df[coluna].quantile(0.50)
    q3 = df[coluna].quantile(0.75)
    iqr = q3 - q1

    li = q1 - 1.5*iqr
    ls = q3 + 1.5*iqr

    assimetria = df[coluna].skew()
    curtose = df[coluna].kurt()

    print(f"Diagnóstico Estatístico de {coluna}\n")
    print(f"Média: {media:.2f}")
    print(f"Mediana: {mediana:.2f}")
    print(f"Moda: {moda}")
    print(f"Desvio padrão: {desvio:.2f}")
    print(f"CV: {cv:.2f}%")
    print(f"Mínimo: {minimo}")
    print(f"Máximo: {maximo}")
    print(f"Amplitude: {amplitude}")
    print(f"Q1: {q1}")
    print(f"Q2: {q2}")
    print(f"Q3: {q3}")
    print(f"IQR: {iqr}")
    print(f'Limite superior = {ls:.2f}')
    print(f'Limite inferior = {li:.2f}')
    print(f"Assimetria: {assimetria:.2f}")
    print(f"Curtose: {curtose:.2f}")

    print("[Média vs Mediana]: ")
    if abs(media - mediana) < tolerancia:
        print(" Distribuição equilibrada. Média e mediana são quase iguais.")
    elif media > mediana:
        print(" Possível cauda longa à direita. Valores altos isolados puxam a média para cima.")
    else:
        print(" Possível cauda longa à esquerda. Valores baixos isolados puxam a média para baixo.")

    print("[Assimetria]:")
    if abs(assimetria) <= tolerancia:
        print(" Distribuição perfeitamente simétrica (ou muito próxima disso).")
    elif assimetria > tolerancia:
        print(" Assimetria Positiva (à direita). A cauda direita é mais longa ou grossa.")
    else:
        print(" Assimetria Negativa (à esquerda). A cauda esquerda é mais longa ou grossa.")

    print("[Curtose]:")
    if abs(curtose) <= tolerancia:
        print(" Caudas e pico semelhantes aos de uma distribuição Normal.")
    elif curtose > tolerancia:
        print(" Caudas pesadas e pico alongado. Indica maior presença de outliers.")
    else:
        print(" Caudas leves e pico achatado. Dados mais espalhados e menos outliers.")

    return df[df[coluna] > ls]

In [ ]:
outliers_celular = diagnostico(crimes_delegacias, "roubo_celular")

Diagnóstico Estatístico de roubo_celular

Média: 7.98
Mediana: 2.00
Moda: 0
Desvio padrão: 13.53
CV: 169.50%
Mínimo: 0
Máximo: 205
Amplitude: 205
Q1: 0.0
Q2: 2.0
Q3: 11.0
IQR: 11.0
Limite superior = 27.50
Limite inferior = -16.50
Assimetria: 3.37
Curtose: 18.77
[Média vs Mediana]:
 Possível cauda longa à direita. Valores altos isolados puxam a média para cima.
[Assimetria]:
 Assimetria Positiva (à direita). A cauda direita é mais longa ou grossa.
[Curtose]:
 Caudas pesadas e pico alongado. Indica maior presença de outliers.

,nome,roubo_celular,roubo_transeunte,munic
0,001ª DP - Praça da República,32,26,Rio de Janeiro
2,005ª DP - Mem de Sá,34,26,Rio de Janeiro
16,021ª DP - Bonsucesso,31,52,Rio de Janeiro
18,023ª DP - Méier,41,32,Rio de Janeiro
24,029ª DP - Madureira,29,39,Rio de Janeiro
...,...,...,...,...
34698,056ª DP - Comendador Soares,44,49,Nova Iguaçu
34700,058ª DP - Posse,44,84,Nova Iguaçu
34701,059ª DP - Duque de Caxias,80,148,Duque de Caxias
34702,060ª DP - Campos Elíseos,43,24,Duque de Caxias
34706,064ª DP - São João de Meriti,34,129,São João de Meriti

In [ ]:
outliers_celular

In [ ]:
outliers_transeunte = diagnostico(crimes_delegacias, "roubo_transeunte")

roubo_transeunte

Média: 35.00
Mediana: 11.00
Moda: 0
Desvio padrão: 51.03
CV: 145.83%
Mínimo: 0
Máximo: 504
Amplitude: 504
Q1: 0.0
Q2: 11.0
Q3: 53.0
IQR: 53.0
Limite superior = 132.50
Limite inferior = -79.50
Assimetria: 2.37
Curtose: 7.77

<StringArray>
[    'Rio de Janeiro',    'Duque de Caxias',        'Nova Iguaçu',
        'São Gonçalo', 'São João de Meriti',            'Niterói',
          'Nilópolis',       'Belford Roxo',           'Mesquita',
           'Itaboraí']
Length: 10, dtype: str

In [ ]:
outliers_transeunte

In [ ]:
correlacao = crimes_delegacias[['roubo_celular','roubo_transeunte']].corr()

correlacao

                  roubo_celular  roubo_transeunte
roubo_celular          1.000000          0.715243
roubo_transeunte       0.715243          1.000000